import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/common/Header";
import { FilterProvider } from "@/context/FilterContext";
import { Footer } from "@/components/common/Footer";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import Loading from "./loading";
import { ThemeProvider } from "@/context/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <FilterProvider>
            <Header />
            <Suspense fallback={<Loading />}>
              <Toaster />
              <main className="min-h-screen bg-background">{children}</main>
            </Suspense>
            <Footer />
          </FilterProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
