import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/common/Header";
import { FilterProvider } from "@/context/FilterContext";
import { Footer } from "@/components/common/Footer";
import { Inter } from "next/font/google"
import { Toaster } from "@/components/ui/sonner"
import { Suspense } from "react";
import Loading from "./loading";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <FilterProvider>
          <Header />
          <Suspense fallback={<Loading />}>
            <Toaster />
            <main className="min-h-screen bg-background">{children}</main>
          </Suspense>
          <Footer />
        </FilterProvider>
      </body>
    </html>
  );
}

